# Generated by Django 4.1.3 on 2022-12-13 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('title', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(max_length=1000, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Music_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicSrc', models.FileField(upload_to='music/')),
                ('cover', models.FileField(upload_to='album_cover/')),
                ('pause_song', models.BooleanField(default=False)),
                ('skip_song', models.BooleanField(default=False)),
                ('fast_forward', models.BooleanField(default=False)),
                ('rewind', models.BooleanField(default=False)),
                ('current_song', models.CharField(max_length=100, null=True)),
                ('duration', models.CharField(default=False, max_length=20)),
                ('name', models.CharField(max_length=100, null=True)),
                ('singer', models.TextField(max_length=1000, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'music',
                'verbose_name_plural': 'musics',
            },
        ),
    ]
