# Generated by Django 4.1.3 on 2022-12-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_music_player_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_player',
            old_name='album_cover',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='music_player',
            old_name='music',
            new_name='musicSrc',
        ),
        migrations.RenameField(
            model_name='music_player',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='music_player',
            old_name='text',
            new_name='singer',
        ),
        migrations.AlterField(
            model_name='music_player',
            name='duration',
            field=models.IntegerField(default=False, max_length=20),
        ),
    ]
