# Generated by Django 4.1.3 on 2022-12-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_album_cover_music_player_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_player',
            name='duration',
            field=models.DurationField(),
        ),
    ]
